### ISSUE TITLE
[question about the performance]

### ISSUE THREAD

**Issue by yichuan-w** [SNU-ARC/Ginex#2]
1. I want to ask why the performance of GINEX is worse than the baseline when I use the ogbn-products dataset?(though I do not have the priviledge to sudo but I think the optimization mentioned in the article should bring speedup even without sudo. I don't know what the problem is.)
2. Also, why can't I find the ali+PG baseline in the code? Thank you for your answers!

attach the performance of ogbn-products:
1.baseline:
 bash-4.4$ PYTHONPATH=/home/yw8143/miniconda3/envs/GNNN/lib/python3.10/site-packages  python3 -W ignore run_baseline.py --dataset ogbn-products
Epoch 00:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 195615/196615 [01:16<00:00, 2560.49it/s]
Epoch 00, Loss: 0.6338, Approx. Train: 0.8321 Epoch time: 76405.7319 ms
2.ginex
PYTHONPATH=PYTHONPATH=/home/yw8143/miniconda3/envs/GNNN/lib/python3.10/site-packages  python3 -W ignore run_ginex.py --neigh-cache-size 6000000000 --feature-cache-size 6000000000 --sb-size 1500 --dataset ogbn-products
Epoch 00: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 196615/196615 [01:24<00:00, 2327.72it/s]
Epoch 00, Loss: 0.6484, Approx. Train: 0.8314
Epoch time: 84480.0799 ms

**Comment by iamjaelee** [comment]
Thanks for your interest in our work.  The main developer of Ginex will be OOO until mid-August, and he will be able to answer after he comes back.  Will appreciate your patience.

**Comment by yichuan-w** [comment]
Additionally, i'd like to aske: "Why does the time taken for each epoch increase when running the baseline? This seems very strange."

**Comment by ilil96** [comment]
Hi Yichuan, 

I have just replied to your email. Please check it out.

**Comment by BearBiscuit05** [comment]
Hello, I also don’t have the privilege to sudo. I want to know if this will affect the performance of the program.

**Comment by ilil96** [comment]
@BearBiscuit05 
Current implementation of Ginex requires sudo privilege as it has to empty the page cache at the start of every superbatch (https://github.com/SNU-ARC/Ginex/blob/fc2c085ad3406508dcf1dc3d750c8d24fb3b17cb/run_ginex.py#L73). While Ginex disables the page cache while executing sample or gather operations, when initializing the feature cache, it loads data with the page cache turned on. Therefore the page cache is not empty at the end of each superbatch execution, and it seems like non-empty page cache negatively affects the superbatch sample process. We have empirically found out that the performance degrades without this command, while more in-depth analysis why this happens.

**Comment by BearBiscuit05** [comment]
Thanks for the reply, I understand.
