### ISSUE TITLE
【Code Question】

### ISSUE THREAD

**Issue by fucker-cracker** [SNU-ARC/Ginex#4]
Could you please tell me where the definition of  function "mt_load_float(line 96 in data.py) "   is?
I see the definition of function "load_float32" in file "mt_load.cpp", but I cannot figure out how these two functions with different names are related.
I am not very familiar with this piece of code. Thank you very much if you could let me know

**Comment by ilil96** [comment]
mt_load is a function for multi-threaded load of int64 data while mt_load_float32 is for loading float32 data.
